

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Foo
    steps:
      - script: echo "Foo"
        condition: always()
  - job: Baar
    condition: always()
    steps:
      - script: echo "baar"
  - job: RA
    condition: Succeeded('Baar')
    steps:
      - script: echo "RA"