pool:
  vmImage: ubuntu-latest

stages:
  - stage: stage1
    jobs:
      - job: job1
  - stage: stage2

    dependsOn: []
    jobs:
    - job: job2
  - stage: stage3
    dependsOn: []
    jobs:
      - job: job3
  - stage: stage4
    dependsOn: []
    jobs:
      - job: job4 
