

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Foo
    steps:
      - script: echo "Foo"
        condition: always()
  - job: Baar
    dependsOn: Foo
    steps:
      - script: echo "baar"
  - job: RA
    dependsOn: Foo
    steps:
      - script: echo "RA"